Task_1_1_2
kocery/OOP pull request #5
Opened 2024-09-14 11:33 UTC by kocery

2024-09-15 06:26 UTC, Sharapov-Maksim requested changes
Хорошая работа, доделывайте. Мягкий дедлайн зачтён

2024-09-15 06:26 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +	Deck deck = new Deck();
> [reviewdog] reported by reviewdog 🐶
Line contains a tab character.

См. [code style](https://google.github.io/styleguide/javaguide.html#s2.3.1-whitespace-characters)

2024-09-15 06:26 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +        dealer.showFirstCard();
Не забудьте что карты дилера бывают закрытыми
![image](https://github.com/user-attachments/assets/ded0aad9-82a7-4e17-ac89-c8d44864da23)

2024-09-15 06:26 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Dealer.java
> +public class Dealer extends Player {
Здорово, что вы уже наследование используете)
Расскажите тогда, что такое наследование и почему вы здесь решили применить этот механизм?

2024-09-15 06:26 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/blackjack/CardTest.java
> +    void testWrongInput1() {
К слову, чтобы снизить вероятность неправильного ввода и убрать дублирование строк в коде, можно будет константы завести

2024-09-15 06:26 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/blackjack/DeckTest.java
> +        String shuffledOrder = deck.getCards().toString();
Такой способ проверки зависит от реализации `Card.toString()`, что не очень надёжно. Лучше всего использовать идентичность объектов для сравнения

2024-09-15 06:26 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/blackjack/PlayerTest.java
> +class PlayerTest {
Ещё бы сценарии с тузами проверить

2024-09-15 06:32 UTC, kocery commented on Task_1_1_2/src/test/java/blackjack/PlayerTest.java
> +class PlayerTest {
у меня подсчёт стоимости туза происходит во время самой игры, так что не вижу возможным покрыть этот аспект, тк игра происходит по сути рандомно

2024-09-15 06:37 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/blackjack/PlayerTest.java
> +class PlayerTest {
Не вижу здесь зависимости на состояние игры, только состояние самого `Player`-а
![image](https://github.com/user-attachments/assets/3d92c3ec-2943-46eb-b8d2-f9ab7d1508e7)

Что вы имеете ввиду?

2024-09-15 06:44 UTC, kocery commented on Task_1_1_2/src/test/java/blackjack/PlayerTest.java
> +class PlayerTest {
ой, извините, перепутал, у меня пару версий было, забыл что так оставил

2024-09-15 06:46 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +        dealer.showFirstCard();
я же в этом куске первую карту только открываю, из-за того, что карта может закрытой я и сделал метод showFirstCard

2024-09-15 07:07 UTC, kocery commented on Task_1_1_2/src/test/java/blackjack/CardTest.java
> +    void testWrongInput1() {
не совсем понял, что вы имеете ввиду

2024-09-15 07:49 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +        dealer.showFirstCard();
Да, но напечатается ли закрытая карта?

2024-09-15 07:53 UTC, Sharapov-Maksim commented on Task_1_1_2/src/test/java/blackjack/CardTest.java
> +    void testWrongInput1() {
Если завести константы вида
```
static String RANK_KING = "Король"
```
то будет сложнее опечататься при их использовании

2024-09-15 08:43 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +        dealer.showFirstCard();
здесь очевидно нет, так я вызываю метод в логике которого показать только одну карту, а далее ситуация, где нужно скрывать карту от игрока не возникнет (в рамках 1 раунда)

2024-09-15 08:44 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +        dealer.showFirstCard();
Судя по примеру из задания, в логике метода показать обе карты, и открытую и закрытую

2024-09-15 08:52 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Dealer.java
> +public class Dealer extends Player {
Потому что в сути набор методов Дилера очень схож с набором методов, нужных для реализации Игрока в блекджек, так что копировать большую часть не эффективно. Дилер - тоже игрок, но в с немного иным поведением, для чего и был добавлен метод `showFirstCard()`, ну и изменён немного вывод руки

2024-09-15 08:52 UTC, kocery commented on Task_1_1_2/src/test/java/blackjack/PlayerTest.java
> +class PlayerTest {
исправил

2024-09-15 08:53 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +	Deck deck = new Deck();
исправил

2024-09-15 08:57 UTC, kocery commented on Task_1_1_2/src/test/java/blackjack/DeckTest.java
> +        String shuffledOrder = deck.getCards().toString();
исправил

2024-09-15 09:01 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +        dealer.showFirstCard();
исправил

2024-09-23 08:57 UTC, Sharapov-Maksim requested changes
Правки выдал

2024-09-23 08:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +public class Blackjack {
Не нашёл в вашей программе метода `main`. Её ведь запускать нужно. Вы сами-то пробовали играть в созданную игру?

2024-09-23 08:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +        playNext();
`playRound` зовёт `playNext`, `playNext` может позвать `playRound`. Не боитесь, что если пользователь будет очень много играть и всегда отвечать что хочет сыграть ещё, то у приложения закончится стек? Давайте всё-таки на обычный игровой цикл переделаем, без рекурсии

2024-09-23 08:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Deck.java
> +        String[] ranks = {"2", "3", "4", "5", "6", "7", "8", "9", "10",
Эти вспомогательные массивы создаются каждый раз в конструкторе. Но ведь они не меняются и одинаковы для всех объектов `Deck`. Так и давайте создадим их один раз и будем разделять между всеми колодами, тут вам могут пригодиться `static` поля

2024-09-23 08:57 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +    public void playRound() {
Если `scanner` сделать аргументом, то метод можно будет протестировать. В тестах можно будет передавать, например, `new Scanner("0\nнет\n")` - раунд в котором игрок отказывается брать карты и продолжать игру. И можно будет сделать тесты на несколько сценариев ответов игрока

2024-09-23 10:29 UTC, daghotur commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +public class Blackjack {
Я main не стал включать в коммиты

```
package blackjack;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Blackjack game = new Blackjack();
        Scanner scanner = new Scanner(System.in);
        game.startGame(scanner);
    }
}
```

2024-09-23 11:20 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +    public void playRound() {
исправил как мог

2024-09-23 11:20 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Deck.java
> +        String[] ranks = {"2", "3", "4", "5", "6", "7", "8", "9", "10",
испарвил

2024-09-23 11:20 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +        playNext();
исправил

2024-09-23 11:37 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +public class Blackjack {
А что помешало включить?

2024-09-23 11:38 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +public class Blackjack {
зачем, логики там явно никакой не будет

2024-09-23 11:50 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +public class Blackjack {
Main это же часть вашего решения. Плюс мне нужно же как-то запускать приложение, чтобы посмотреть что всё работает

2024-09-23 11:50 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +    public void playRound() {
Здорово, даже целиком игру получилось потестировать, это хорошо

2024-09-23 12:18 UTC, Sharapov-Maksim requested changes

2024-09-23 12:18 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +                    System.out.println("Спасибо за игру!");
Предлагаю выделять одинаковые строчки в переменные, чтобы опечататься было сложнее

2024-09-23 13:52 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +                    System.out.println("Спасибо за игру!");
исправил

2024-09-23 13:52 UTC, kocery commented on Task_1_1_2/src/main/java/blackjack/Blackjack.java
> +public class Blackjack {
добавил

2024-09-24 06:01 UTC, Sharapov-Maksim approved these changes
Замечания исправлены. Задание засчитано, ветку можно мёржить

2024-09-24 13:11 UTC, merged