Task_1_1_3
kocery/OOP pull request #6
Opened 2024-09-15 13:10 UTC by kocery

2024-09-28 09:25 UTC, Sharapov-Maksim commented
Что-то у вас в этот PR затянулись файлы из прошлого задания. Такого не стоит допускать, ревьюить менее удобно

2024-09-28 09:47 UTC, Sharapov-Maksim requested changes
Хорошая работа, нужно только доделать требуемую функциональность. Мягкий дедлайн зачтён.

И напомню, что в этом задании можно выполнять доп. условия и получать доп. баллы

2024-09-28 09:47 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/mathexp/Expression.java
> +public sealed abstract class Expression
Нужно добавить метод, который по строке строит Expression
![image](https://github.com/user-attachments/assets/b7aee0e2-e2c1-4958-8f0c-163b411f181d)

2024-09-28 10:56 UTC, kocery commented
> Хорошая работа, нужно только доделать требуемую функциональность. Мягкий дедлайн зачтён.
> 
> И напомню, что в этом задании можно выполнять доп. условия и получать доп. баллы

А сколько доп баллов?

2024-09-29 05:21 UTC, Sharapov-Maksim commented
> А сколько доп баллов?

По одному за каждое доп. условие. В данной задаче - максимум 2

2024-09-30 16:02 UTC, Sharapov-Maksim requested changes
Осталось только тестов немного добавить

2024-09-30 16:02 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/mathexp/Mul.java
> +        return new Mul(simplifiedLeft, simplifiedRight);
Непокрытый тестами сегмент.
Чтобы увидеть, какие части покрыты тестами, можно, например, воспользоваться IDEA:
![image](https://github.com/user-attachments/assets/9bbbebdc-4110-4f48-bed8-517f0a8ae30b)
И строчки, которые ни разу не исполнились входе тестов, будут помечены красным
![image](https://github.com/user-attachments/assets/36e341ee-313d-47bb-bcd4-bde362bb3e1b)

Следовательно, нужны ещё тестовые сценарии, которые покроют этот код

2024-09-30 16:02 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/mathexp/Div.java
> +        return new Div(simplifiedLeft, simplifiedRight);
Покрыть тестами

2024-09-30 16:02 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/mathexp/ExpressionParserTest.java
> +public class ExpressionParserTest {
Стоит добавить тест на сложное выражение совсем без скобок

2024-10-02 14:39 UTC, Sharapov-Maksim approved these changes
Задание засчитано, PR можно мёржить

2024-10-03 10:03 UTC, merged