Task_1_3_1
kocery/OOP pull request #9
Opened 2024-10-23 05:29 UTC by kocery

2024-10-26 14:25 UTC, Sharapov-Maksim requested changes
Хорошая работа, мягкий дедлайн зачтён

2024-10-26 14:25 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/substringfinder/SubstringFinderTest.java
> +    private static void generateLargeTestFile(String filename, String pattern, int repetitions)
После генерации файл остаётся лежать в корневой директории проекта. Давайте добавим удаление файла в конце теста

2024-10-26 14:25 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/substringfinder/SubstringFinderTest.java
> +            "The number of occurrences does not match the expected value");
Для такой простой генерации тестовых данных (паттернов, разделённых пробелами), можно и сами индексы в `occurrences` проверить тоже

2024-10-26 14:25 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/substringfinder/SubstringFinderTest.java
> +public class SubstringFinderTest {
Давайте сделаем небольшие тесты на краевые случаи, например: find ("aaaaaa", "a"), find("ababababa", "aba"), пустую подстроку

2024-10-26 14:25 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/substringfinder/SubstringFinderTest.java
> +public class SubstringFinderTest {
И сделаем один тест с очень большими данными, прямо размером с гигабайт, или несколько. Хотя допускаю, что наш CI может и не справиться с таким - напишите если будут трудности.

Также нужно будет провести эксперимент: запустить данный тест с ограниченным размером кучи (см. `-Xmx` VM option, например: `-Xmx256m` для файла в 1GB), проверить, что он не падает с OutOfMemory. При этом стоит сделать тест так, чтобы не раздувать список `occurences`, желательно чтобы найденное вхождение было одно или их не было вовсе. Об условиях и результатах эксперимента напишите комментарий =)

2024-11-09 08:49 UTC, kocery commented on Task_1_3_1/src/test/java/substringfinder/SubstringFinderTest.java
> +    private static void generateLargeTestFile(String filename, String pattern, int repetitions)
метод `tearDown()` удаляет все тестовые файлы, проверял локально

2024-11-09 09:21 UTC, kocery commented on Task_1_3_1/src/test/java/substringfinder/SubstringFinderTest.java
> +public class SubstringFinderTest {
все получилось, файл выходит около гига в размере, с флагом на ограничение все работает, CI тоже не упал, что приятно)

2024-11-10 06:47 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-11-10 09:55 UTC, merged